#!/usr/bin/env bash
# installer for socketchat (docker version, linux only)
# usage: curl -fsSL https://raw.githubusercontent.com/ALHANSHIM/SocketChat/main/installer.sh | bash
set -e

IMAGE="${SOCKETCHAT_IMAGE:-alhanshim/socketchat:latest}"
BIN_DIR="$HOME/.local/bin"
TARGET="$BIN_DIR/schat-docker"


if [ "${1:-}" = "--uninstall" ]; then
    rm -f "$TARGET"
    echo "removed $TARGET (the docker image is still there, remove it with: docker rmi $IMAGE)"
    exit 0
fi

if [ "$(uname -s)" != "Linux" ]; then
    echo "error: linux only (you have $(uname -s)). on windows/mac just do pip install -e . instead" >&2
    exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found, install it first: https://docs.docker.com/engine/install/" >&2
    exit 1
fi

if ! docker info >/dev/null 2>&1; then
    echo "error: docker is not running, start it first (sudo systemctl start docker)" >&2
    exit 1
fi

echo "checking for $IMAGE ..."
if docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "image already there, skipping download"
else
    echo "pulling $IMAGE ..."
    docker pull "$IMAGE"
fi

mkdir -p "$BIN_DIR"

cat > "$TARGET" <<'LAUNCHER_EOF'
#!/usr/bin/env bash
# generated by the socketchat installer, no need to edit this
set -e
IMAGE="${SOCKETCHAT_IMAGE:-alhanshim/socketchat:latest}"

if ! command -v docker >/dev/null 2>&1; then
    echo "error: docker not found" >&2
    exit 1
fi

if ! docker info >/dev/null 2>&1; then
    echo "error: docker is not running (try: sudo systemctl start docker)" >&2
    exit 1
fi

if ! docker image inspect "$IMAGE" >/dev/null 2>&1; then
    echo "image $IMAGE not found, pulling it..."
    docker pull "$IMAGE"
fi

exec docker run --rm -it --network host "$IMAGE" "$@"
LAUNCHER_EOF

chmod +x "$TARGET"
echo "installed $TARGET"


case ":$PATH:" in
    *":$BIN_DIR:"*) ;;
    *)
        if [ -f "$HOME/.bashrc" ]; then
            LINE='export PATH="$HOME/.local/bin:$PATH"'
            if ! grep -Fqx "$LINE" "$HOME/.bashrc" 2>/dev/null; then
                echo "$LINE" >> "$HOME/.bashrc"
                echo "added $BIN_DIR to PATH in ~/.bashrc"
            fi
        fi
        echo "NOTE: $BIN_DIR is not on your PATH right now. restart your terminal or run:"
        echo '  export PATH="$HOME/.local/bin:$PATH"'
        ;;
esac

echo "done. just run: schat-docker"
