[project]
name = "socketchat"
version = "0.1.0"
description = "LAN chat "
requires-python = ">=3.10"
dependencies = [
    "textual",
    "click",
    "cryptography",
    "rich",
]


[project.scripts]
schat = "socketchat.commands:schat"


[tool.setuptools]
packages = ["socketchat", "socketchat.tui"]


[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
